controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        $empresas = \app\models\Empresa::find()->orderBy('rand()')->all();
        $empresas = $this->renderPartial('//empresa/_list', ['empresas' => $empresas]);
        $enquadr = \app\models\Enquadramento::find()->all();
        return $this->render('index', [
                    'enquadramento' => $enquadr,
                    'empresas' => $empresas
        ]);
    }

    public function actionSearch() {
        $params = Yii::$app->request->post('Empresa');
        $aux = '';
        $query = \app\models\Empresa::find();

        foreach ($params as $key => $param) {
            $query->andFilterWhere(['like', $key, $param]);
        }
        return $this->renderPartial('//empresa/_list', ['empresas' => $query->all()]);
    }

}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

$this->title = 'Teste Lançador de Ofertas';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Lançador de Ofertas!</h1>

        <p class="lead">Pesquise nos campos abaixo:</p>


    </div>

    <div class="body-content">
        <form id='frmSearch' action='<?= yii\helpers\Url::toRoute(['site/search']) ?>' method="post" onsubmit="enviaDados(this); return false;">
            <input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>" />
            <div class="row">
                <div class="col-md-3">
                    <label for="enquadramento">
                        Enquadramento
                    </label>
                    <select id="enquadramento" name="Empresa[enquadramento_id]" class="form-control">
                        <option value=''></option>
                        <?php
                        if (isset($enquadramento)) {
                            foreach ($enquadramento as $enqd) {
                                ?>
                                <option value="<?= $enqd->id ?>"><?= $enqd->enquadramento ?></option>
                                <?php
                            }
                        }
                        ?>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="empresa">
                        Empresa
                    </label>
                    <input type="text" name="Empresa[nome]" id="empresa" class="form-control"/>
                </div>
                <div class="col-md-3">
                    <label for="cidade">
                        Cidade
                    </label>
                    <input type="text" name="Empresa[cidade]" id="cidade" class="form-control"/>
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-success btn-search form-control"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
        <br/>
        <div class="row" id='response'>
            <?= $empresas ?>
        </div>
    </div>
</div>
<script>

    function enviaDados(element) {
        let form = $("#" + element.id);
        let action = form.attr('action');
        let data = form.serialize();
        $.ajax({
            url: action,
            type: "POST",
            data: data,
            dataType: "html",
            beforeSend: function (xhr) {
                $("#response").fadeOut('slow');
            }
        }).done(function (resposta) {
            $("#response").fadeIn('slow').html(resposta);
        }).fail(function (jqXHR, textStatus) {
            console.log("Request failed: " + textStatus);
        }).always(function () {
            console.log("completou");
        });
    }
</script>